[package]
name = "server"
version = "0.1.0"
authors = ["Murali Mohan Rath <murali@mmrath.com>"]

[dependencies]
rocket = "0.2.6"
rocket_codegen = "0.2.6"
rocket_contrib = "0.2.6"
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
lazy_static = "0.2.8"

